services:
  db:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pikachu17
      POSTGRES_DB: Biblioteca

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Biblioteca"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgres://postgres:pikachu17@db:5432/Biblioteca
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pikachu17
      DB_NAME: Biblioteca
      JWT_SECRET: clave_secreta_8fK92LmPq7xZs4RtBvN3Yh6Cd

    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: